name: Build scribble documentation
on:
  push:
    branches:
      - main
    paths:
      - 'scribblings/**'

jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.7
        with:
          distribution: 'full'
          variant: 'CS'
          version: 'stable'
          
      - name: Install dependencies (from info.rkt)
        run: raco pkg install --auto --batch

      - name: Scribble documentation              
        run: raco scribble --htmls --dest doc --redirect-main https://docs.racket-lang.org +m scribblings/whatnow.scrbl

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: doc/whatnow
          CLEAN: true
          
